# to be run with `docker build -v ${PWD}:/app -f Dockerfile-script`
# script is located in `./boop-scripts/pem-decode/target`
# See: https://github.com/IvanMathy/Boop/blob/main/Boop/Documentation/ConvertingNodeModules.md

FROM docker.io/library/node:lts
LABEL authors="daniel@sigterm.de"

WORKDIR /app/boop-scripts/pem-decode/src
RUN npm init -y && npm install node-forge
RUN npx -y browserify PEMCertificateDecoder.js -o tmp/PEMCertificateDecoderBundle.js
RUN npx terser tmp/PEMCertificateDecoderBundle.js -o tmp/PEMCertificateDecoderBundle.min.js
WORKDIR /app/boop-scripts/pem-decode/
RUN mkdir -p target
RUN cat src/PEMCertificateDecoder_header.js src/tmp/PEMCertificateDecoderBundle.min.js > target/PEMCertificateDecoder.js
